# 
control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
kps: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
kds: [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]

default_angles: [0.1, 0.9, -1.8, 0.1, 0.9, -1.8,
                 0.1, 0.9, -1.8, 0.1, 0.9, -1.8]

arm_waist_joint2motor_idx: [12, 13, 14, 
                            15, 16, 17, 18, 19, 20, 21, 
                            22, 23, 24, 25, 26, 27, 28]


ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 48

max_cmd: [0.8, 0.5, 1.57]
