# 
control_dt: 0.02

msg_type: "go"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "/home/rajath/Documents/Go2_mjx/utils/outputs/go2_policy-127.onnx"

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
kps: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

default_angles: [0.1, 0.9, -1.8, -0.1, 0.9, -1.8,
                 0.1, 0.9, -1.8, -0.1, 0.9, -1.8]

crounch_angles: [-0.35, 1.36, -2.65, 0.35, 1.36, -2.65,
                 -0.5, 1.36, -2.65, 0.5, 1.36, -2.65]


ang_vel_scale: 0.1
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.3
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 57

max_cmd: [0.8, 0.5, 1.57]
